#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

require __DIR__ . '/vendor/autoload.php';

try {
    $dotenv = Dotenv\Dotenv::create(__DIR__.'');
    $dotenv->load();
} catch (\Throwable $th) {
    throw $th;
}

defined('YII_DEBUG') or define('YII_DEBUG', getenv('YII_DEBUG'));
empty(getenv('YII_ENV')) ?: defined('YII_ENV') or define('YII_ENV', getenv('YII_ENV'));

require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/config/console.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
